[[generative_typography]]
=== Generative Typography Platform with Processing - Project in Progress


What areas or field does it fall in::
   ((Typography)), ((Generative)), ((Design))
What tools did you use?
   ((Processing)), ((Geomerative Library))

video::http://player.vimeo.com/video/50550549[height='313', width='500', poster='images/typography_poster.png']

==== Description

This project is a basic prototype for a generative typography tool made with Processing using the link:http://www.ricardmarxer.com/geomerative/[Geomerative Library] by Ricard Marxer. It came out of Rune Madsen's class at ITP in generative design. In his lectures, Madsen stresses the important of limitations alongside flexibility. Building software systems that can provide flexibility while allowing a designer to work within their self-definied limits is difficult but ultimately extremely useful. Additionally, in the world of generative design there area a lot of generative fonts popping up, but no way to customize them on with your own tools. This interface offers an alternative system that is open, fully customizeable, and flexible. A lot of work still needs to be done to make this a full-fledged tool, so have at it!

I highly recommend checking out the documentation for the link:https://github.com/matthewepler/generative_type_platform[Geomerative library] to get a better idea of what it's capable of doing inside this platform. 

==== Bio

Matthew Epler is a graduate student at NYU's Interactive Telecommunications Program (ITP) specializing in computational art and archives.

URL::
   http://mepler.com/
Contact Information::
   matthewepler@gmail.com
Tags::
   ((processing)) ((typography)) ((generative)) ((student))