[[R]]
=== R: The R Project for Statistical Computing
   
*Site:* + http://www.r-project.org/ +
*Git or Code:* http://cran.r-project.org/mirrors.html +
*Wikipedia:* http://en.wikipedia.org/wiki/R_%28programming_language%29 +
*Other wiki/resource:* http://rwiki.sciviews.org/doku.php[R Wiki] 


 
==== Quickest Possible Description
R is a language and environment for statistical computing and graphics. It's an open source version / different implementation of S. Originally written by Robert Gentleman and Ross Ihaka of the Univeristy of Auckland, it is now collaborative effort with its own foundation and core contributors. It's widely used for data analytics, data mining, machine learning, data visualization. It's what you need for Big Data projects, basically. R is particularly useful because it's so extensible. Thousands of packages have been written to help R handle certain kinds of data from climate information to speech. This http://cran.r-project.org/web/views/["Task View"]page offers an overview of some of the ways R has been applied.


==== Frequently Used For
Data visualization +
Analytics +
Machine Learning +
Basic and Advanced Statistics (modeling, distributions, tests, etc) +
Handling GeoSpatial data, medical research, signal processing, etc +
data mining



==== Important Details
GNU General Public License +
Runs on UNIX including Windows, MacOS, FreeBSD, Linux

 

==== Heavyweights
Dianne Cook +
Bill Venables +
http://en.wikipedia.org/wiki/John_Chambers_%28statistician%29[John Chambers] (creator of S, core committer of R) +
Jake Porway +
Amanda Cox

==== Projects & Examples 
http://blog.revolutionanalytics.com/2012/09/3-d-animation-of-the-changing-antarctic-ice-sheet.html[3-D Animation of the changing antarctic ice sheet] +
http://blog.revolutionanalytics.com/2012/09/video-song-map.html[Video Map of the hottest songs in the US] +
a bunch of great projects from http://www.periscopic.com[periscopic]

==== Resources / Community / Support 

*Tutorials* +
http://www.revolutionanalytics.com/news-events/free-webinars/2012/introduction-to-r-for-data-mining/[Introduction to R for Data Mining] (Webinar) +
http://channel9.msdn.com/Events/Lang-NEXT/Lang-NEXT-2012/Why-and-How-People-Use-R[Why and How people Use R] by John Cook (presentation) +
http://jeffreybreen.wordpress.com/2012/10/02/tapping-the-data-deluge-with-r/
http://www.slideshare.net/jeffreybreen/tapping-the-data-deluge-with-r[Tapping the Data Deluge with R] - by Jeff Breen (lightning talk) +
http://www.johndcook.com/R_language_for_programmers.html[Tutorial: R for programmers coming from different languages] by John Cook +
http://burns-stat.com/pages/Tutor/hints_R_begin.html[Some Hints For The R Beginner] by Patrick Burns +
http://www.burns-stat.com/pages/Tutor/R_inferno.pdf[The R Inferno] by Patrick Burns (PDF) +
http://google-styleguide.googlecode.com/svn/trunk/google-r-style.html[Google's R Style Guide]
http://flowingdata.com/category/tutorials/[A bunch of great tutorials] from Flowing Data
http://cran.r-project.org/doc/manuals/R-intro.html[an introduction to R]



*Books* +
http://datajournalismhandbook.org[datajournalismhandbook.org] +
http://shop.oreilly.com/product/9780596801717.do[R In A Nutshell]
http://www.amazon.com/gp/product/0470944889/?tag=flowingdata-20+[Visualize This]
http://www.manning.com/kabacoff/[R in Action - Data Analysis and Graphics with R] by Robert Kabacoff
http://www.r-project.org/doc/bib/R-books.html[Books Related To R] (a list, not a book)


*Blogs & Websites* +
http://www.inside-r.org/howto/finding-data-internet[Finding Data on the Internet] (This blog post lists data sources that are easily imported into R or already in R format)
http://www.statmethods.net/[www.statmethods.net] A great blog with lots of information from the author of R In Action. +
http://blog.revolutionanalytics.com/[David Smith's R blog] +
http://citizen-statistician.org/[Citizen Statistician] (a blog about stats that talks a lot about R) +
http://journal.r-project.org/current.html[R Journal: Articles & News about R] +
http://flowingdata.com[flowingdata.com] +


*Community / Support* +
http://cran.R-project.org/faqs.html[Cran R project FAQ] +
http://www.inside-r.org/[inside-R] +
http://www.r-project.org/mail.html[R-Help Mailing List] +
http://www.r-project.org/other-docs.html[project documentation]


==== Similarly Awesome and Useful Tools
http://cran.r-project.org/web/packages/Rook/index.html[Rook] - R package for building and running R web applications +
http://rstudio.org[RStudio] - IDE for R +
http://elastic-r.net[elasticR] - Package for using EC2 with R +
http://socserv.mcmaster.ca/jfox/Misc/Rcmdr/[R Commander] - Basic-Statics GUI for R +
http://www.revolutionanalytics.com/products/revolution-r.php[RevolutionR] - Enterprise software for R (with academic and free versions) +
http://www.bioconductor.org/[Bioconductor] open source development project to provide packages and tools for analysis and comprehension of high-throughput genomic data.  +
http://cran.r-project.org/web/views/[CRAN Task Views Page] +
http://crantastic.org/[Crantastic] Community site for R Packages +
http://code.google.com/p/r4intellij/[R 4 IntelliJ:] - Integration of R into the intellij DEA +
