[[Cinder]]
=== Cinder

Cinder is an open source C++ library for creative coding. Think of it as a non-Java alternative to Processing. It was originally developed by the Barbarian Group for their interactive advertising projects, which required something more robust than Processing for programming graphics, audio & video, image processing, and computational geometry. It can be considered as a next-step beyond Processing, which is better for learning to code. Cinder shares many attributes with openFrameworks, and an aspiring user should investigate both tools, along with Processing.

.Quickest Possible Description
****
Description::
    The non-Java alternative to Processing.
Site::
   http://libcinder.org
Git::
   https://github.com/cinder/Cinder
Wikipedia::
   http://en.wikipedia.org/wiki/Cinder_(programming_language)
****

==== Frequently Used For

Frequently used for: 

* Interactive screen-based work
* Physical installations
* Increasingly used for iphone/ipad apps

==== Important Details

Important details include:

* Supports Mac OS X (with XCode), Windows, and IOS
* Released under link:http://www.oss-watch.ac.uk/resources/modbsd.xml[Simplified BSD License]

==== Heavyweights

The heavyweights in the field include:

* link:http://drawnline.net/[Andrew Bell] was the originator and lead architect.
* link:http://roberthodgin.com/[Robert Hodgin] wrote the book on it.

==== Projects & Examples 

Interesting projects and examples include:

* link:http://planetary.bloom.io/[Planetary]—Visual exploration of your music collection
* link:http://marcinignac.com/projects/cindermedusae/[Cindermedusae]—Generative sea creatures

==== Resources / Community / Support

Useful resources include:

Tutorials::
   * link:http://libcinder.org/docs/v0.8.4/hello_cinder.html[Hello Cinder]—tutorial by Robert Hodgin
Books::
   * link:http://shop.oreilly.com/product/0636920024095.do[Exploring Cinder], by Joshua Noble and Robert Hodgin
Community::
   * link:http://forum.libcinder.org/#allForums[Cinder forums] 


==== Similarly Awesome and Useful Tools

Similar tools include http://www.smallab.org/code/ccgl/[CCGL] and  http://www.smallab.org/code/ccgl-touch/[CCGL-Touch], Cinder wrappers for OSX and iOS

