[[OpenCV]]
=== OpenCV
   
*Site:* http://opencv.org + 
*Git:* git://code.opencv.org/opencv.git +
*Wikipedia:* http://en.wikipedia.org/wiki/OpenCV +
*Twitter:* http://twitter.com/#!/opencvlibrary +
*OpenCV Wiki:* http://code.opencv.org/projects/opencv/wiki +

==== Quickest Possible Description
OpenCV is an open source computer vision and machine learning software library. It's widely used and supported by people working on real-time computer vision such as face detection, camera tracking, augmented reality, and anything else cool that you see done with cameras. The library has thousands of algorithms that can be used to detect and recognize faces, identify objects, classify human actions in videos, track camera movements, track movement, extract 3D models of objects, produce 3D point clouds from stereo cameras, stitch images together, find similar images from a database, recognize scenery and establish markers for augmented reality applications, and much, much more.

OpenCV is actively managed by http://itseez.com/[itseez] and http://opencv.willowgarage.com/wiki/[Willow Garage]


==== Frequently Used For
Face & Gesture recognition +
Human - Computer Interaction +
Motion Tracking +
Robotics +
Stereopsis  +
Machine Learning (Detection / Recognition)  +
Camera Calibration  +
Image Processing

==== Important Details
Released under a BSD license (free to use)  +
Has C++, C, Python & Java interfaces  +
Supports Windows, Linux, Android, Mac OS  +

==== Heavyweights
 +
 +


==== Projects & Examples 
http://cvdazzle.com/[CV Dazzle] by Adam Harvey +
http://www.ros.org/wiki/[robot operating system ] +
http://www.youtube.com/watch?v=bBQQEcfkHoE i3D - Head Tracking for iPad + 
http://www.aikon-gold.com/ [Aikon] - home of Paul The Robot by Patrick Tresset +
http://www.engadget.com/2011/10/21/t-i-m-art-installation-has-a-taste-for-passers-by-also-fava-be/ [T.I.M] +
http://www.creativeapplications.net/objects/apparel-by-the-normals-clothes-that-evolve-in-real-time-with-the-user/[Apparel by the normals] +
http://normalfutu.re[normalfutu.re] +

==== Resources / Community / Support 

*Tutorials* +
http://www.embedded.com/design/other/4372167/Introduction-to-embedded-vision-and-the-OpenCV-library[Introduction to embedded vision and the OpenCV library] - Eric Gregori
 
*Books* +
http://www.cs.iit.edu/~agam/cs512/lect-notes/opencv-intro/opencv-intro.html[Introduction To programming with OpenCV] by Gady Agam +
http://shop.oreilly.com/product/0636920022497.do[Learning OpenCV, 2nd Edition] by Gary Bradski, Adrian Kaehler +
http://www.packtpub.com/opencv-2-computer-vision-application-programming-cookbook[OpenCV 2: Computer Vision Application Programming Cookbook] by Robert Laganière


*Blogs & Websites* +
 +


*Community / Support* +
http://code.opencv.org/projects/opencv/wiki[OpenCV Wiki] +
http://docs.opencv.org[PpenCV Documentation] +
http://answers.opencv.org/questions/[OpenCV Questions] +
http://tech.groups.yahoo.com/group/OpenCV/[Yahoo OpenCV Group]

==== Similarly Awesome and Useful Tools 
SimpleCV http://simplecv.org/[website] & http://simplecv.tumblr.com[tumblr] +
http://www.mathworks.com/products/matlab/[MatLab]
