[[OpenFrameworks]]
=== OpenFrameworks

* Site: http://www.openframeworks.cc/
* Git: https://github.com/openframeworks/openFrameworks
* Wikipedia: http://en.wikipedia.org/wiki/OpenFrameworks
* Twitter: https://twitter.com/openframeworks
* Other wiki/resource: http://wiki.openframeworks.cc/

 
==== Quickest Possible Description
openFrameworks is an open source pass:[C++] toolkit designed to make creative coding easier. Its creators describe it as a "general purpose glue" that wraps together common libraries such as OpenGL, OpenCV, FreeType and many more. It is designed to be cross-platform and extensible, and to provide a promote experimentation with both software interfaces that allow for interesting real-time screen-based and physical interactions. openFrameworks shares many similarities with Processing and especially Cinder, which is also a C++ library framework. It makes sense to investigate all three when deciding on a creative coding tool.


==== Frequently Used For
Physical Installations +
Big Screens +
Physical & Screen Based Interaction Projects


==== Important Details:
Open Source, distributed under the https://en.wikipedia.org/wiki/MIT_License[MIT License] +
Platforms: Windows, OSX, Linux, iOS, Android +
IDEs: XCode, pass:[Code::]Blocks, Visual Studio, Eclipse


==== Heavyweights:
Zach Lieberman https://twitter.com/zachlieberman[@zachlieberman] | http://thesystemis.com/ +
Arturo Castro https://twitter.com/artur0castro[@artur0castro] | http://arturocastro.net/ +
Kyle McDonald ‏ https://twitter.com/kcimc[@kcimc] | http://kylemcdonald.net/ +
Theo Watson ‏ https://twitter.com/theowatson[@theowatson] | http://www.theowatson.com/ +
Chris O’Shea ‏ https://twitter.com/chrisoshea[@chrisoshea] | http://www.chrisoshea.org/ +
Evan Roth https://twitter.com/fi5e[@fi5e] | http://www.evan-roth.com/work/ +
Golan Levin: http://twitter.com/golan[@golan] | http://flong.com/ +

==== Projects & Examples: 
made with openFrameworks: +
video::http://player.vimeo.com/video/921725[height='377', width='500', poster='images/generic_video.png']

http://eyewriter.org/[Eyewriter] +
http://thesystemis.com/projects/drawn/[Drawn] +
http://arturocastro.net/work/faces.html[Faces] by Arturo Castro & Kyle McDonald +
http://www.chrisoshea.org/body-swap[Body Swap] +
http://vimeo.com/44489751[Blind Self Portrait] by Kyle McDonald +
http://design-io.com/site_docs/work.php?id=13[Night Bright] by Design I/O +
http://www.creativeapplications.net/iphone/hana-by-andreas-muller-allows-ios-devices-to-dream-about-flowers/[Hana] by Andreas Muller +
https://github.com/HeliosInteractive/ofxIisu[Hand tracking experiment] by Ben McChesney +
http://faceshift.com/[FaceShift (face tracking)] +
http://www.ni9e.com/graffiti_analysis.html[Graffiti Analysis] by Evan Roth +


==== Resources / Community / Support: 
 
*Tutorials* +
http://www.openframeworks.cc/tutorials/[openframeworks.cc/tutorials/] has excellent tutorials, and is a great place to start +
http://www.itee.uq.edu.au/~comp3300/Resources/C_C++_notes.pdf[C and pass:[C++ in 5 days]] by Philip Machanick (PDF) +
http://wiki.openframeworks.cc/index.php?title=OF_for_Processing_users[OF for Processing Users] by Zach Gage, for those transitioning from Processing +
http://www.sparkfun.com/tutorials/318[Using openFrameworks with Arduino] +
https://github.com/benMcChesney/Open-Frameworks-Tutorials[OF Frameworks Tutorials] by Ben McChesney +

*Books* +
http://oreilly.com/catalog/9780596154141/[Programming Interactivity] by Joshua Noble +

*Community* +
http://www.openframeworks.cc/list-info/[Mailing List] +
http://forum.openframeworks.cc/index.php[Forum]  +

==== Similarly Awesome and Useful Tools
  
http://ofxaddons.com[ofxaddons] A directory of extensions and libraries for OpenFrameworks +

https://github.com/ofTheo/ofxKinect[ofxKinect], an OF add-on for the Xbox Kinect +



