[[PureData]]
=== PureData (PD)

Pure Data: An open source alternative to Max, originally developed by the same developer, Miller Puckette. Labeled as a 'real-time music and multimedia environment' it allows manipulation of video, graphics, and music, and enables live collaboration across networks between musicians. It's multi-platform and portable so it can run on all sorts of devices and can be extended, just like Max. 

.Quickest Possible Description
***
Site:: http://puredata.info/[Project homepage]
Wikipedia:: http://en.wikipedia.org/wiki/Max[Max], http://en.wikipedia.org/wiki/Pure_Data[Pure Data]
Other wiki/resource:: http://puredata.info/docs[Docs from project homepage]
Code:: http://www-crca.ucsd.edu/~msp/software.html
Email list:: http://lists.puredata.info/pipermail/pd-list/
***

==== Frequently Used For

Major uses include:

* Realtime media manipulation
* Interactive art with sound and video
* Mobile apps


==== Important Details
 
Details include:

* PD is free and licensed under http://opensource.org/licenses/bsd-license.php[BSD].
* Most associated software is licensed under http://www.gnu.org/copyleft/copyleft.html[GNU GPL].

==== Heavyweights

The heavyweights in the field include http://crca.ucsd.edu/~msp/[Miller Puckette], originator of PD.

==== Projects & Examples 

Interesting projects and examples include Jamie Oliver's http://www.jaimeoliver.pe/instrumentos/silent-drum[Silent Drum].

==== Resources / Community / Support 

Tutorials:

* A huge collection of http://puredata.info/docs/workshops[workshops] and http://puredata.info/docs/tutorials[tutorials] is available on the PD site.
* http://obiwannabe.co.uk/tutorials/html/tutorials_main.html[Practical Synthetic Sound Design] (tutorial by Andy Farnell).
* http://blog.makezine.com/2012/09/24/protodrom-prototyping-with-pure-data-and-processing/[Prototyping with Pure Data and Processing].
* http://crca.ucsd.edu/~msp/techniques/latest/book-html/[The Theory and Technique of Electronic Music] by Miller Puckette.
* http://www.youtube.com/user/cheetomoskeeto#grid/user/12DC9A161D8DC5DC[video lectures] by Dr.Hdez.

Books:

* http://pd-tutorial.com/[Loadbang: Programming Electronic Music in PD] by Johannes Kreidler
* http://shop.oreilly.com/product/0636920022503.do[Making Musical Apps – Real-Time Audio Synthesis on Android and iOS] by Peter Brinkmann (2012)
* http://www.amazon.com/Composition-Pure-Data-Meta-Compositional-Instrument/dp/3838316479[Composition: Pure Data as a Meta-Compositional Instrument] by Michael Barkl (2012)
* http://amzn.to/SX6DMh[Pd Recipe Book―Pure Data] by Sei Matsumura
* http://mitpress.mit.edu/catalog/item/default.asp?ttype=2&tid=12282[Designing Sound] by Andy Farnell (2010)

Blogs & Websites:

http://en.flossmanuals.net/puredata/[The Pure Data manual]

Community / Support:

http://puredata.info/community/IRC[IRC]

==== Similarly Awesome and Useful Tools
  
http://libpd.cc/[Libpd] is "PD made embeddable." It strips away the GUI and the concerns with inputs and outputs, to give a lightweight version of PD which is better suited to mobile development. You can find https://github.com/libpd[libpd on GitHub].