[[Cinder]]
=== Cinder
   
* Site: http://libcinder.org
* Git: https://github.com/cinder/Cinder
* Wikipedia: http://en.wikipedia.org/wiki/Cinder_(programming_language)
   

Key areas::
   (((area 1))), (((area 2)))

==== Key resources 

List the key resources with links here (blogs, books, etc).

* Resource 1. http://example.com is a great place to find inspirational examples.
* Resource 2. http://example.com is a the spot for how-to articles and technical resources.

==== Key people

Ben Fry::
   link:http://benfry.com/[Ben Fry] is principal of Fathom, a design and software consultancy located in Boston. He received his doctoral degree from the Aesthetics + Computation Group at the MIT Media Laboratory, where his research focused on combining fields such as computer science, statistics, graphic design, and data visualization as a means for understanding information. After completing his thesis, he spent time developing tools for visualization of genetic data as a postdoc with Eric Lander at the Eli & Edythe L. Broad Insitute of MIT & Harvard. During the 2006-2007 school year, Ben was the Nierenberg Chair of Design for the Carnegie Mellon School of Design. At the end of 2007, he finished writing Visualizing Data for O'Reilly. In 2011, he won the National Design Award for Interaction Design from the Cooper-Hewitt.

Dan Shiffman:: 
   link:http://www.shiffman.net/[Daniel Shiffman] works as an Assistant Arts Professor at the Interactive Telecommunications Program at NYU’s Tisch School of the Arts. Originally from Baltimore, Daniel received a BA in Mathematics and Philosophy from Yale University and a Master’s Degree from the Interactive Telecommunications Program. He works on developing tutorials, examples, and libraries for Processing, the open source programming language and environment created by Casey Reas and Ben Fry. He is the author of Learning Processing: A Beginner’s Guide to Programming Images, Animation, and Interaction and The Nature of Code (self-published via Kickstarter), an upcoming text and series of code examples about simulating natural phenomenon in Processing. 


==== Overview

This section should have a list of examples that give the reader a flavor of what the tool is and what it's used for.

==== Quickest Possible Description:
Cinder is an open source C++ library for creative coding. Think of it as a non-Java  alternative to Processing. It was originally developed by the Barbarian Group for their interactive advertising projects, which required something more robust than Processing for programming graphics, audio & video, image processing, and computational geometry. It can be considered as a next-step beyond Processing, which is better for learning to code. 

==== Frequently Used For:
Creative Coding. Simple as that.
Often used for physical installations
Increasingly used for iphone/ipad apps


==== Important Details:
Supports Mac OS X (with XCode), Windows (with Visual C++), and IOS
Released under Simplified BSD License (http://www.oss-watch.ac.uk/resources/modbsd.xml)

==== Heavyweights:
Andrew Bell - Originator and Lead Architect (http://drawnline.net/)
Robert Hodgin - Wrote the book on it. (http://roberthodgin.com/)

==== Projects & Examples: 
Planetary - Visual exploration of your music collection. http://planetary.bloom.io/
Cindermedusae - Generative sea creatures: http://marcinignac.com/projects/cindermedusae/

==== Resources / Community / Support: 
 
Hello Cinder - tutorial by Robert Hodgin: 
http://libcinder.org/docs/v0.8.4/hello_cinder.html
Exploring Cinder by Joshua Noble and Robert Hodgin 
http://shop.oreilly.com/product/0636920024095.do

Cinder Forums:
http://forum.libcinder.org/#allForums


==== Similarly Awesome and Useful Tools:
  
CCGL and CCGL-Touch - Cinder Wrappers for OSx and iOS:
http://www.smallab.org/code/ccgl/
http://www.smallab.org/code/ccgl-touch/
